### ISSUE TITLE
'Edit Footer/Header' buttons don't work

### ISSUE THREAD

**Issue by lumberman** [live-composer/live-composer-page-builder#1006]
'Edit Footer/Header' buttons don't work in editing mode.

**Comment by livecomposer** [comment]
@lumberman confirmed this today while working on Cloudios: https://cl.ly/90ae22b6a191

**Comment by TSNH** [comment]
I have the exact same problem as lumberman shows in his video.  Note that the problem manifests itself differently in Chrome and Internet Explorer.  In Chrome, it's the same as in lumberman's video.  In Internet Explorer, the Element boxes appear but some of the Element editing tabs don;t display the white text.  I'm wondering if this is a Java related issue since I've experienced Java related issues on other websites with both browsers.

**Comment by TSNH** [comment]
I just tried an experiment and it worked.  I still have the same "edit header" / "edit footer" problem that does't do anything when I click them, so I instead did a right-click and then did "Open link in new tab".  The tab showed just the header (or footer), but it allowed me to fully edit the header and footer and save the results.  FYI, the link for the header is "http://domainname.com/wp-admin/admin.php?page=livecomposer_editor&page_id=105" and for the footer is "http://domainname.com/wp-admin/admin.php?page=livecomposer_editor&page_id=102", where "domainname.com" is of course not the real domain name.
