### ISSUE TITLE
Doesn't work with WordPress 5.5

### ISSUE THREAD

**Issue by Leo-domenic** [live-composer/live-composer-page-builder#1047]
Immediately after updated the latest WordPress 5.5, Live Composer didn't work anymore. It's impossible to edit elements or to save changes. Only rows can be edited, but changes not saved.
Please fix this issue, I cannot use my website anymore.

**Comment by andyrr-kiel** [comment]
Yes @Leo-domenic is right: The error-warning:
ReferenceError: mqMutationObserver is not defined
File "https://domain/wp-content/plugins/live-composer-page-builder/js/dist/editor_backend.min.js?ver=1582254739", line 8, char 81421

I try it with LC 1.5.6 and 1.5.7 with the same result.

Greets Andy

**Comment by bandicootmarketing** [comment]
Hi @Leo-domenic and @andyrr-kiel . We are working on a solution for this and will get it figured out as fast as we can. It may be a few days before we can provide a fix so in the meantime, please revert your site back to WP 5.4. Cheers.

**Comment by andyrr-kiel** [comment]
This is exactly what i´m doing, im downgrade to 5.4 :-)

Thx for reply!
Greets Andy

**Comment by Leo-domenic** [comment]
> Hi @Leo-domenic and @andyrr-kiel . We are working on a solution for this and will get it figured out as fast as we can. It may be a few days before we can provide a fix so in the meantime, please revert your site back to WP 5.4. Cheers.

Thanks for reply and for your efforts!

**Comment by livecomposer** [comment]
We have found and fixed the issue. Please log into your account at https://livecomposerplugin.com/wp-login.php and go to your Downloads and download the latest version of the LC Extensions plugin (1.3.2). It will fix the compatibility error with WP 5.5.
We CANNOT provide support here in Github, so please use the Support form inside your account for any questions (the issue is only with LC Extensions and LC support is now limited to paid customers). Cheers and thanks for everyone's patience!
