### ISSUE TITLE
Needs update with 5.5 - my website doesn't work!

### ISSUE THREAD

**Issue by anna0911** [live-composer/live-composer-page-builder#1048]
With some help from Wordpress professionals, i found out that the live composer page builder and the extensions are not compatible with wordpress 5.5 Please fix this. My complete website does not load and nobody can visit. Could you please fix this issue?

**Comment by anna0911** [comment]
For now, i found a solution in the jQuery plugin. My site is luckily on display. This however, does not allow me to actually use the live composer. Which means i can't make any changes at all. And that's too bad, because i will be going on vacation next week, and wanted to upgrade some content. Please, can you fix this issue fast?

**Comment by bandicootmarketing** [comment]
Hi @anna0911 - we received your ticket through Envato support. We are working on a solution for this and will get it figured out as fast as we can. It may be a few days before we can provide a fix so in the meantime, please revert your site back to WP 5.4. Cheers.

**Comment by JaimeUNA** [comment]
I also have this problem. I love this plugin, congratulations to the development team, I know they will resolve it soon! 

Thank you very much

**Comment by bandicootmarketing** [comment]
Hi @JaimeAugusto - thanks so much for the kind words. We are working on it as fast as we can!

**Comment by livecomposer** [comment]
We have found and fixed the issue. Please log into your account at https://livecomposerplugin.com/wp-login.php and go to your Downloads and download the latest version of the LC Extensions plugin (1.3.2). It will fix the compatibility error with WP 5.5.

We CANNOT provide support here in Github, so please use the Support form inside your account for any questions (the issue is only with LC Extensions and LC support is now limited to paid customers). Cheers and thanks for everyone's patience!

**Comment by anna0911** [comment]
Hi, i cannot access https://livecomposerplugin.com/wp-login.php. I keep getting the same issue. See picture attached. Any help?
![Schermafbeelding 2020-08-13 om 09 33 51](https://user-images.githubusercontent.com/69592877/90106781-308aad80-dd48-11ea-8360-756be4cb2c3a.png)

**Comment by JaimeAugusto** [comment]
Good morning, will the update be made available with wordpress? 

Thank you very much
