### ISSUE TITLE
After your Update - Even the same error in WP 5.5

### ISSUE THREAD

**Issue by andyrr-kiel** [live-composer/live-composer-page-builder#1050]
JavaScript error detected in a third-party plugin
ReferenceError: mqMutationObserver is not defined
File "https://domain/wp-content/plugins/live-composer-page-builder-1.5.7/js/dist/editor_backend.min.js?ver=1597309758", line 8, char 81717

WP 5.5
PHP 7.47

and we have the paid version of Live Composer - Premium Extensions and he cannot update to 1.32, still 1.3

we test it with lc version 1.5.6 and 1.5.7 - no changes

So what to do?

Greets Andy

**Comment by livecomposer** [comment]
Hi @andyrr-kiel - thanks for following up. The bug is ONLY with LC Extensions, and you must update to version 1.3.2 to see a resolution. We have many users who have followed this process and found success. I'm not sure what you meant by "cannot update" to 1.3.2, but that update needs to happen. Was there an error message when the update was attempted? If you are still on Premium Extensions 1.3 you will still see the issue.
