### ISSUE TITLE
We need help with testing PRESETS functionality in module options

### ISSUE THREAD

**Issue by livecomposer** [live-composer/live-composer-page-builder#135]
I believe this feature can be affected by all the code changes we made over the last two months. We need your help with testing all the aspects of this feature.

Please report any bugs here.

Thank you.

**Comment by menachemshapiro** [comment]
Not exactly a bug report, but I have some comments on the presets features.

At the moment, the presets feature is very difficult to use for several reasons:  
1) There is no way to tell what settings the presets are saving, and which ones they aren't.
1b) Without using the preset (and overwriting the setting you already have) There is no what to tell what the settings that have been saved are.
2) There is no way to remove a preset, which means that they start stacking up.
3) When wanting to add to an existing preset (so that the change you make affects all the other modules using the same preset), there is no real indication that you've done it. In my experience (and this could be due to bugs or my own ineptitude) it seems like sometimes changes are made and propagated to all other modules, and some times they aren't.
3b) There should also be a way to apply the settings of a preset and doing nothing more, so that any changes made do not change the rest of the modules.

I think this can be solved by expanding the preset section. There is a lot of room in the preset tab, so it shouldn't be an issue:
1) have a way to show what the presets settings actually are
2) have a way to delete presets
3) make it more clear when the preset has taken affect.
4) have a clear option to add to the saved preset
4b) with the option not to add the changes to the saved preset if you don't want to
5) BONUS FEATURE: have a way to export presets, so you can share them with people, or whatever.

**Comment by menachemshapiro** [comment]
I'm not sure if this is a bug or intended behavior, but when I disabled Shadow Text in one of my preset Text modules, it did not change it in the other modules that used the same preset.

On the other hand, changing all the shadow text options to 0 but leaving it enabled, did change the rest of the module.

**Comment by menachemshapiro** [comment]
Another Shadow Text related issue. I added some blur to the "Content" of one of my preset text modules. Some of the other modules picked up this change, but others didn't. I'm not sure why. It is on this webpage: http://emilyatal.com/

The following sections have Shadow Text:
Villa Bonita
Banana Beach Bungalows
Live the Dream in Santa Teresa
Vacation Planning

Did not pick up the change:
Banana Beach Restaurant
Destinations Weddings

Let me know if you need any other information from me.

**Comment by FoldingTheme** [comment]
#882
