### ISSUE TITLE
Development Function to Extend Module Options?

### ISSUE THREAD

**Issue by jessicahawkins3344** [live-composer/live-composer-page-builder#424]
I am not referring to the dev feature of being able to export the module defaults for altering module options. I want to know what is the best way, if any to **add to module options**, like adding a margin-top option if one doesn't exist for that module.

Secondly, what hook can be used to alter or change a modules output, or html without altering the core plugin code itself? Rather than having to simply create an entirely new module.... thanks.

**Comment by lumberman** [comment]
Thanks for your question Jessica.

The best way to extend options is send your request here and we will add it in the master branch + next update.

All the module options are going through the next filter:
`return apply_filters( 'dslc_module_options', $dslc_options, $this->module_id );`

You can use it like this:
```
function jessica_module_options_ext( $module_options_array, $module_id ) {

	if ( 'DSLC_Button' === $module_id ) {
		$module_options_array[] = array(
			'label' => __( 'Control Label', 'jessica' ),
			'id' => 'css_conrol_name',
			'std' => '0',
			'type' => 'slider',
			'refresh_on_change' => false,
			'affect_on_change_el' => '.dslc-button',
			'affect_on_change_rule' => 'margin-top',
			'section' => 'styling',
			'ext' => 'px',
		);
	}

 	return $module_options_array;
  }
add_filter( 'dslc_module_options', 'jessica_module_options_ext', 10, 2 );
```

**PLEASE NOTE:**
We are working on Live Composer 2nd Generation. The new page builder will use CSS classes instead of having custom properties for each module. So if you have a button style created once you will be able to reuse for all the buttons on the website without multiplying CSS lines in the source code. 

Here how it will looks like:
<img width="326" alt="screen shot 2016-12-03 at 12 25 23 pm" src="https://cloud.githubusercontent.com/assets/1384471/20861693/9fc22fa6-b953-11e6-9a98-98efc4f29e15.png">

Taking in account these future changes it's better us to put more controls for you in the core to make sure you not looks these properties in the future (we will migrate all the standard controls automatically).

------

Second part: Module prints the output directly. there is no way now to filter output. Sorry.

**Comment by jessicahawkins3344** [comment]
hey @lumberman -this new feature that will be made available in the 2nd generation is awesome! i will just wait until then!

**Comment by jessicahawkins3344** [comment]
For now, I am simply creating new modules if I want to change the layout output of an exisiting module.

**Comment by jessicahawkins3344** [comment]
When will the gen 2 be available for testing?
