### ISSUE TITLE
Staff Post Type Social Links not Working in Single Post

### ISSUE THREAD

**Issue by IkeTen** [live-composer/live-composer-page-builder#466]
The social media links for the social media links for staff single posts don't work for some social media links.
I have confirmed this issue with especially Instagram profile links. 
Nearly thought this was a feature but the builder social links show all socials but when saved and published some go missing

**Comment by xdima92x** [comment]
Hi @IkeTen I tested the module 'Staff'. It works properly. Could you [open a ticket](https://livecomposerplugin.com/support/support-request/) and send login details for Wordpress?

**Comment by xdima92x** [comment]
Hi @IkeTen Do you say about module 'Staff' or module 'Staff Social'? I tested these modules and they are work properly.  Could you open a ticket - https://livecomposerplugin.com/support/support-request/ and send login details on Wordpress for testing.

**Comment by IkeTen** [comment]
@xdima92x  I mean the staff social module. It does not show all staff social links on the staff single posts. It shows only facebook and twitter.

**Comment by xdima92x** [comment]
Hi @IkeTen It's not a bug because the default module shows four social links. I have improved and now you can add [all social links](https://www.evernote.com/shard/s554/sh/44cd064d-66af-4393-94db-762f5fb52c38/27097244f5cdedcb). Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/466 Please [add social links here](https://www.evernote.com/shard/s554/sh/be7017ba-823b-42cd-a8af-563196d6d89f/bc5e726f3696ab7e)

**Comment by xdima92x** [comment]
Hi @lumberman Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/466

**Comment by IkeTen** [comment]
Thanks for the fix @xdima92x  and @lumberman . Works great!
