### ISSUE TITLE
Icons in accordion and tab title

### ISSUE THREAD

**Issue by ArekZw** [live-composer/live-composer-page-builder#805]
![image](https://user-images.githubusercontent.com/11788346/30657445-ec5d9700-9e37-11e7-8ae2-f7bcf3895228.png)

![image](https://user-images.githubusercontent.com/11788346/30657472-ffc01a20-9e37-11e7-8f79-e99584e2f5f5.png)

**Comment by jgajera** [comment]
+1 on this, I've tried hardcoding icons in, and they all disappear after
the accordion is toggled. I have not tried to add icons with Javascript,
but I assume same issue since accordion toggle doesn't reload the page.
Would be nice if everything was within LC for beginner users anyway, rather
than recommending to use Javascript or a workaround.

**Comment by xdima92x** [comment]
I'm sorry but it's impossible to add different icons for every title. We added icon plus and minus for module accordion

**Comment by FoldingTheme** [comment]
the icons status need to be improved:
![01_test___seowp](https://user-images.githubusercontent.com/21088706/46854656-4193cc00-ce0a-11e8-8b3b-cc4b84ba1ef9.png)
