### ISSUE TITLE
[Cache] Can't disable cache - post update issues

### ISSUE THREAD

**Issue by 101010f** [live-composer/live-composer-page-builder#843]
The cache option in Performance seems to cause some issues with new posts. They only appear on admin's PC. I disabled the option but I still have to clear cache every time for it to work on other device. Any workaround please?

**Comment by lumberman** [comment]
@101010f can you please describe a step-by-step process to recreate this bug?

**Comment by 101010f** [comment]
@lumberman I create a new post, The new post shows on the PC I logged in with but not on other PCs even if I clear the cache locally from the browser. I then have to clear the HTML cache on your plugin refresh page on other PC to see the changes. That's pretty much it. 
I checked with the hosting provider and the server cache is not activated so it's pretty much the plugin.

**Comment by lumberman** [comment]
@101010f I can't recreate this issue on my machine. We do reset all the cache once you save any post or the page: https://github.com/live-composer/live-composer-page-builder/blob/422174b01749a036f18ad4299a85769e858b65ce/includes/class-dslc-cache.php#L104

Are you sure not to use a service like CloudFlare that can cache your pages "outside" your server?

I can do further debugging if you provide login details via support (at) livecomposer.io but most likely it's something to do with your setup otherwise many other users would report it earlier.

I'll keep this ticket open for a while to see any other cases like this.

**Comment by 101010f** [comment]
@lumberman The thing is, I have other websites on that particular hosting provider using other wordpress themes and there is not a similar issue.
This is the only website I used live-composer on and it's a fresh install. I'll provide you with an admin account on support if you have the time to check it out.

**Comment by lumberman** [comment]
@101010f sure send your details privately.

**Comment by 101010f** [comment]
@luberman I've sent it to support (at) livecomposer.io
