### ISSUE TITLE
Change Widgets on Live Composer Tab = Broken LC Templates

### ISSUE THREAD

**Issue by emingus** [live-composer/live-composer-page-builder#849]
From WP Admin > Live Composer > Settings > Widget Module

Add new widget title "Test" > Save

Use Search Bar to search keyword "love"

Gives me "LC Powered Page needs to be set..." message.

All plugins except LiveComposer deactivated. 

Anyone else having this issue?

**Comment by lumberman** [comment]
Hi Enigmus. 

Are you using any of our themes? 
Live Composer can manage every part of your website. Most likely you have this issue because there is now Search results listing template. 

1) You can create a new template for search results in **WP Admin > Appearance > Templates > Add Template** 
2) When creating a new template set it to **Search Results** in Template Options panel.
<img width="961" alt="add_template_ _live_composer_ _wordpress" src="https://user-images.githubusercontent.com/1384471/33794172-c0a18574-dc83-11e7-9277-7552adc07f61.png">
3) Open this template in Live Composer and place at least POSTS module on it.
<img width="1069" alt="edit__search_results" src="https://user-images.githubusercontent.com/1384471/33794179-fff4f5a8-dc83-11e7-950b-c2079f77ba6b.png">


Let me know how it goes...

**Comment by emingus** [comment]
I'm using Orao.

**Comment by emingus** [comment]
And yes, I have that on my site. But I have to actually go in and resave it for it to "fix" itself after editing modules.

**Comment by lumberman** [comment]
If you have this problem solved I'm closing the issue. Please reopen if still help needed.

**Comment by emingus** [comment]
It's not solved. There is a workaround, but I figured you might want to check into it. I already found another issue that I was credited for helping to find.
