### ISSUE TITLE
Add/Feature Rewrite Javascript with mithril.js framework

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#856]
Rewriting all complex stuff and ensuring usage of virtual dom with fastest framework available would make this builder the fastest builder on WordPress.

**Comment by lumberman** [comment]
It will require rewriting all the modules to be JS based/rendered. If we go this way we will lose PHP/shortcodes rendering previews and will need to drop back-compatibility. Solutions are ugly. Check modules in Elementor (they duplicate code in PHP/js) or Gutenberg (they mostly use placeholders and ugly rendering scheme).

Most likely Gutenberg will take the biggest share of the page-builder users, so our target is to adopt LC to work with it better instead of trying to oppose it.
