### ISSUE TITLE
Project Images Slider keeps loading

### ISSUE THREAD

**Issue by Ligitas24** [live-composer/live-composer-page-builder#923]
Hi, 
I ran into problem when trying to use Project Images Slider. When I add this element to the template, element just keeps loading but nothing else happens.  It doesn't matter how long I will wait - nothing shows. I can select this element and change settings, but there is still nothing on the screen, just loading icon. Also if I save everything and add photo to project, nothing shows up, when I open page of that project. 
I'm using Live Composer 1.3.15.

I hope that's enough information to solve this problem!

**Comment by FoldingTheme** [comment]
Most likely it is caused by a third-party plugin conflict. Please check this article: https://livecomposer.help/article/196-basic-debugging-process

If still need assistance after debug, please open a support ticket and provide an admin access: https://livecomposerplugin.com/support/support-request/
