### ISSUE TITLE
Image module resize fields

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#963]
At this moment the feature works when both of the fields for "width" and "height" are filled. Check the possibility to have them working independently. For instance, when just the "Width" field is set.

**Comment by xdima92x** [comment]
At this moment we use this function '[image_resize_dimensions](https://codex.wordpress.org/Plugin_API/Filter_Reference/image_resize_dimensions)' for resize. We need to use the two required parameters ( width and height ).

**Comment by thehervy** [comment]
So does it mean that we need use both dimensions all the time? Or it will be fixed in the future? :) Thank you.

**Comment by xdima92x** [comment]
Hi @thehervy It's not a problem with LC. The module 'image' used height and width ( how is required parameters ) earlier for resize because the LC use this function  'image_resize_dimensions' for resize. We need to use the two required parameters ( width and height ). You can read this about this function - https://developer.wordpress.org/reference/functions/image_resize_dimensions/
image_resize_dimensions - is WordPress Core. It is not possible with the way the page builder is coded at this moment. Maybe later we will add it.
